// JavaScript Document
var pic_width=950; 
var pic_height=328; 
var button_pos=4; 
var stop_time=3000; 
var show_text=0; 
var txtcolor="000000"; 
var bgcolor="DDDDDD"; 
var imag=new Array();
var link=new Array();
var text=new Array();
imag[1]="images/banner1.jpg";
link[1]="#";
text[1]="图片1";
imag[2]="images/banner2.jpg";
link[2]="#";
text[2]="图片2";
imag[3]="images/banner3.jpg";
link[3]="#";
text[3]="图片3";
imag[4]="images/banner4.jpg";
link[4]="#";
text[4]="图片4";
imag[5]="images/banner5.jpg";
link[5]="#";
text[5]="图片5";
imag[6]="images/banner6.jpg";
link[6]="#";
text[6]="图片6";
imag[7]="images/banner7.jpg";
link[7]="#";
text[7]="图片7";
var swf_height=show_text==1?pic_height+20:pic_height;
var pics="", links="", texts="";
for(var i=1; i<imag.length; i++){
	pics=pics+("|"+imag[i]);
	links=links+("|"+link[i]);
	texts=texts+("|"+text[i]);
}
pics=pics.substring(1);
links=links.substring(1);
texts=texts.substring(1);
document.write('<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cabversion=6,0,0,0" width="'+ pic_width +'" height="'+ swf_height +'">');
document.write('<param name="movie" value="flash/focus.swf">');
document.write('<param name="quality" value="high"><param name="wmode" value="opaque">');
document.write('<param name="FlashVars" value="pics='+pics+'&links='+links+'&texts='+texts+'&pic_width='+pic_width+'&pic_height='+pic_height+'&show_text='+show_text+'&txtcolor='+txtcolor+'&bgcolor='+bgcolor+'&button_pos='+button_pos+'&stop_time='+stop_time+'">');
document.write('<embed src="flash/focus.swf" FlashVars="pics='+pics+'&links='+links+'&texts='+texts+'&pic_width='+pic_width+'&pic_height='+pic_height+'&show_text='+show_text+'&txtcolor='+txtcolor+'&bgcolor='+bgcolor+'&button_pos='+button_pos+'&stop_time='+stop_time+'" quality="high" width="'+ pic_width +'" height="'+ swf_height +'" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />');
document.write('</object>');
